---
name: Backport

on:
  workflow_dispatch: {}

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/backport@2e217641d82d02ba0603f46b1aeedefb258890ac # v2.0.3
        with:
          github_token: ${{ secrets.SCIMIA_BOT_GITHUB_TOKEN }}
