---
name: Backport

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'backport-')
    steps:
      - name: Backport Action
        uses: sqren/backport-github-action@v8.9.7
        with:
          github_token: ${{ secrets.SCIMIA_BOT_GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-
          add_original_reviewers: true

