name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    steps:
      - name: Step One
        run: uuidgen
