name: Run Tests

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    steps:
      - uses: actions/checkout@v3

      - name: Run Flaky Tests
        id: flaky
        continue-on-error: true
        env:
          VERBOSE: ${{ runner.debug == '1' && '1' || '' }}
        run: ./tests.sh flaky

      - name: Run Tests
        if: steps.flaky.outcome == 'failure'
        env:
          VERBOSE: ${{ runner.debug == '1' && '1' || '' }}
        run: ./tests.sh
