---
name: Run Tests

on:
  workflow_dispatch: {}
  pull_request_target: {}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          set -x
          ./tests.sh
